import SideBar from "@/components/Shared/SideBar";

export const metadata = {
  title: "dashboard layout",
  description: "Generated by create next app",
};

const DashboardLayout = ({ children }) => {
  return (
    <div className="flex">
      <SideBar></SideBar>
      <div className="w-full">{children}</div>
    </div>
  );
};

export default DashboardLayout;
